# Generated by Django 4.2 on 2023-04-08 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carteras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('fecha_compra', models.DateField()),
                ('precio', models.FloatField()),
                ('color', models.CharField(max_length=15)),
                ('dimensiones', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=15)),
                ('ano_origen', models.IntegerField()),
                ('contacto', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('carteras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.carteras')),
            ],
        ),
        migrations.AddField(
            model_name='carteras',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.marca'),
        ),
    ]
