# Generated by Django 3.2.5 on 2023-04-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('fecha_compra', models.DateField()),
                ('precio', models.FloatField()),
                ('color', models.CharField(max_length=15)),
                ('dimensiones', models.CharField(max_length=15)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.marca')),
            ],
        ),
        migrations.RenameModel(
            old_name='Carteras',
            new_name='Cartera',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
