# Generated by Django 3.2.5 on 2023-04-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20230409_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartera',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='carteras/'),
        ),
        migrations.AddField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='marcas/'),
        ),
        migrations.AddField(
            model_name='zapato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='zapatos/'),
        ),
    ]
