# Generated by Django 3.2.5 on 2023-05-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_datauser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataUser',
        ),
    ]
