# Generated by Django 4.2 on 2023-05-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_conversacion_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='emisor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha_envio',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='conversacion',
        ),
        migrations.DeleteModel(
            name='Conversacion',
        ),
    ]
